openapi: 3.0.2
info:
  title: Model-CNS API
  description: API to access MoDEL-CNS data and files.
  version: 1.0.0

servers:
  - url: '{protocol}://mmb.irbbarcelona.org/webdev2/MoDEL-CNS/api/rest/{version}'
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
      version:
        enum:
          - v1
          - current
        default: v1

paths:
  /project:
    get:
      summary: Get a list of projects.
      description: Get a list of MoDEL-CNS projects (simulations and related data and analyses).
      parameters:
        - name: limit
          in: query
          description: pagination, maximum number of projects per query
          schema:
            type: integer
            default: 10
            maximum: 50
        - name: page
          in: query
          description: pagination, page number
          schema:
            type: integer
            default: 1
      responses:
        200:
          description: an array of projects, paginated
          content:
            application/json:
              schema:
                type: object
                properties:
                  projects:
                    type: array
                    items:
                      $ref: '#/components/schemas/Project'
                  count:
                    type: integer
  /project/{projectIdentifier}:
    get:
      summary: Get a project by its identifier.
      description: Get a MoDEL-CNS project (simulations and related data and analyses) by its identifier.
      parameters:
        - name: projectIdentifier
          in: path
          description: project identifier
          required: true
          schema:
            type: string
      responses:
        200:
          description: a project
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'

components:
  schemas:
    Analysis:
      type: object
    File:
      type: object
      properties:
        _id:
          type: string
          pattern: '^[0-9a-f]{24}$'
        length:
          type: integer
        filename:
          type: string
        md5:
          pattern: '^[0-9a-f]{32}$'
    Project:
      type: object
      properties:
        identifier:
          type: string
          pattern: '^MCNS[0-9]{5}$'
        metadata:
          type: object
          additionalProperties:
            oneOf:
              - type: string
              - type: number
              - type: integer
        pdbInfo:
          type: object
        analyses:
          type: array
          items:
            $ref: '#/components/schemas/Analysis'
        files:
          type: array
          items:
            $ref: '#/components/schemas/File'
