openapi: 3.0.2
info:
  title: Model-CNS API
  description: API to access MoDEL-CNS data and files.
  version: 1.0.0

servers:
  - url: '{protocol}://mmb.irbbarcelona.org/webdev2/MoDEL-CNS/api/rest/{version}'
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
      version:
        enum:
          - v1
          - current
        default: v1

paths:
  /project:
    get:
      summary: Return a list of projects.
      description: Return a list of MoDEL-CNS projects (simulations and related data and analyses).
      responses:
        200:
          description: an array of projects, paginated
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'

components:
  schemas:
    Analysis:
      type: object
    File:
      type: object
      properties:
        _id:
          type: string
          pattern: '^[0-9a-f]{24}$'
        length:
          type: integer
        filename:
          type: string
        md5:
          pattern: '^[0-9a-f]{32}$'
    Project:
      type: object
      properties:
        identifier:
          type: string
          pattern: '^MCNS[0-9]{5}$'
        metadata:
          type: object
          additionalProperties:
            oneOf:
              - type: string
              - type: number
              - type: integer
        pdbInfo:
          type: object
        analyses:
          type: array
          items:
            $ref: '#/components/schemas/Analysis'
        files:
          type: array
          items:
            $ref: '#/components/schemas/File'
